# Cheatsheet

*License: CC-BY-NC-SA 4.0*

*Author: Murilo M. Marinho (murilo.marinho@manchester.ac.uk)*

## Installation

In [ ]:
%%capture
%pip install numpy
%pip install roboticstoolbox-python
%pip install numpy --break-system-packages
%pip install roboticstoolbox-python --break-system-packages

## Imports

In [37]:
import numpy as np
import spatialmath as sm
from math import pi

## Converting from `spatialmath` to `numpy`

### SE(2)

In [38]:
import numpy as np
import spatialmath as sm
from math import pi

# SE(2)
HA = sm.SE2(1,2,pi/2)
print(HA)

# Useful conversions
# Rotation
RA_np = HA.R
# Position
pA_np = HA.t
# (full) Transformation
HA_np = HA.A

print(f"The original SE(2) object was \n{HA}\n and can be converted to: ")
print(f"\tA rotation matrix \n{RA_np}\n that has size = {RA_np.shape}.")
print(f"\tA position vector \n{pA_np}\n that has size = {pA_np.shape}.")
print(f"\tA homogenous transformation matrix \n{HA_np}\n that has size = {HA_np.shape}.")



   0        -1         1         
   1         0         2         
   0         0         1         

The original SE(2) object was 
   0        -1         1         
   1         0         2         
   0         0         1         

 and can be converted to: 
	A rotation matrix 
[[ 6.123234e-17 -1.000000e+00]
 [ 1.000000e+00  6.123234e-17]]
 that has size = (2, 2).
	A position vector 
[1. 2.]
 that has size = (2,).
	A homogenous transformation matrix 
[[ 6.123234e-17 -1.000000e+00  1.000000e+00]
 [ 1.000000e+00  6.123234e-17  2.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00]]
 that has size = (3, 3).


### SE(3)

In [39]:
import numpy as np
import spatialmath as sm
from math import pi

# SE(3)
HB = sm.SE3(1,2,3) * sm.SE3().Rz(pi/2)
print(HB)

# Useful conversions
# Rotation
RB_np = HB.R
# Position
pB_np = HB.t
# (full) Transformation
HB_np = HB.A

print(f"The original SE(2) object was \n{HB}\n and can be converted to: ")
print(f"\tA rotation matrix \n{RB_np}\n that has size = {RB_np.shape}.")
print(f"\tA position vector \n{pB_np}\n that has size = {pB_np.shape}.")
print(f"\tA homogenous transformation matrix \n{HB_np}\n that has size = {HB_np.shape}.")

   0        -1         0         1         
   1         0         0         2         
   0         0         1         3         
   0         0         0         1         

The original SE(2) object was 
   0        -1         0         1         
   1         0         0         2         
   0         0         1         3         
   0         0         0         1         

 and can be converted to: 
	A rotation matrix 
[[ 6.123234e-17 -1.000000e+00  0.000000e+00]
 [ 1.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00]]
 that has size = (3, 3).
	A position vector 
[1. 2. 3.]
 that has size = (3,).
	A homogenous transformation matrix 
[[ 6.123234e-17 -1.000000e+00  0.000000e+00  1.000000e+00]
 [ 1.000000e+00  6.123234e-17  0.000000e+00  2.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00  3.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]
 that has size = (4, 4).


## Comparing `numpy` matrices

Owing to floating point limitations of computers, use, in general, `numpy.allclose`.

In [40]:
import numpy as np
import spatialmath as sm
from math import pi, sin, cos

# SE(2) with spatialmath
HC = sm.SE2(1,2,pi/2)

# SE(2) directly from numpy
HC_np = np.array(
        [[cos(pi/2), -sin(pi/2),  1],
         [sin(pi/2),  cos(pi/2),  2],
         [0,            0,        1]]
)

# Compare HC.A and HC_np
print(np.allclose(HC.A, HC_np))

True
