# About this Notebook

*License: CC-BY-NC-SA 4.0*

*Author: Murilo M. Marinho (murilo.marinho@manchester.ac.uk)*

### Pre-requisites
The user of this notebook is expected to have prior knowledge in
- Basic Python [[Tutorial]](https://docs.python.org/3/tutorial/index.html)
- Numpy 
    - [[Tutorial: basics for beginners]](https://numpy.org/doc/stable/user/absolute_beginners.html)
    - [[Tutorial: for MATLAB users]](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html)
- Jupyter Notebook Basics [[Tutorial]](https://docs.jupyter.org/en/latest/)

### I found an issue
Thank you! Please report it at https://github.com/MarinhoLab/OpenExecutableBooksRobotics/issues

### Macros (do not touch these)

$\providecommand{\myvec}[1]{{\mathbf{\boldsymbol{{#1}}}}}$
$\providecommand{\mymatrix}[1]{{\mathbf{\boldsymbol{{#1}}}}}$

# A quick Python refresher

## Variable assignment 

Let

$$a\triangleq 10,b\triangleq 5.$$

We can replicate the above in Python with

In [211]:
a = 10
b = 5

## Output variables
Variables can be output using `print`. For example, for $a$

In [212]:
print(a)

10



### Output text and variables using f-strings
To output $a$ and $b$ within a string, we can use `print` and f-strings as follows

In [213]:
print(f'The value of a = {a} and b = {b}.')

The value of a = 10 and b = 5.


# Basic Arithmetics

Basic mathematical operations are trivially performed as follows.

#### Sum

$$c = a + b.$$

In [214]:
c = a + b

print(f'c={c}')

c=15


#### Subtraction
$$c = a - b.$$

In [215]:
c = a - b

print(f'c={c}')

c=5


#### Multiplication
$$c=a.b$$

In [216]:
c = a * b

print(f'c={c}')

c=50


#### Division
$$c = \frac{a}{b}$$

In [217]:
c = a / b

print(f'c={c}')

c=2.0


### Exponentiation
$$c = a^{b}$$

In [218]:
c = a ** b

print(f'c={c}')

c=100000


### Square root

$$c = \sqrt{a}$$

In [219]:
from math import sqrt # Note that the import needs only, in general, be called once per script

c = sqrt(a)

### n-th root
The nth root,

$$c= \sqrt[n]{a}, n \in \mathbb{N},$$

does not seem to have a shorthanded version in Python, but can computed through simple properties such as

$$c = \sqrt[n]{a} = a^{\frac{1}{n}} = e^{\frac{ln(a)}{n}}.$$

For example, suppose that

$$n = 3.$$ 

Then,

In [220]:
n=3

and we can calculate the n-th root like so

In [221]:
# n-th root using fractional exponent. Might be easier but most languages do not support a similar syntax
c = a ** (1/n)

print(f'c={c}')

c=2.154434690031884


or like so

In [222]:
# n-th root using exp/log
from math import exp, log

c = exp(log(a)/n)

print(f'c={c}')

c=2.154434690031884


and both should output the same value.

### Trigonometric functions

$$ \phi = \frac{\pi}{4},$$
$$ s_{\phi} = \sin \left( \phi \right),$$
$$ c_{\phi} = \cos \left( \phi \right),$$
$$ t_{\phi} = \tan \left( \phi \right).$$

In [223]:
from math import pi, sin, cos, tan

phi = pi/4.0
s_phi = sin(phi)
c_phi = cos(phi)
t_phi = tan(phi)

print(f'phi={phi}')
print(f's_phi={s_phi}')
print(f'c_phi={c_phi}')
print(f't_phi={t_phi}')

phi=0.7853981633974483
s_phi=0.7071067811865475
c_phi=0.7071067811865476
t_phi=0.9999999999999999


# Linear Algebra with Numpy

### Installing the library

Just in case `numpy` is not already installed, we can install it with the following command. Nothing will happen if the library is already installed.

In [224]:
%pip install numpy --break-system-packages


[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python3.12 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


### Importing the library

<div class="alert alert-block alert-info">
In this notebook we will import the module each time we use it, for clarity. However, for a regular Python script, you only need to do that once in general.
</div>

In [225]:
import numpy as np

### Instantiating vectors
A row vector can be instanteated from a list of list. For instance, for 
$$\myvec{v} = \left[\begin{array}{ccc}
         1 & 2 
        \end{array}\right],
$$
we have

In [226]:
import numpy as np 

# Note the double [[]] to instanteate a vector with explicit row shape.
v = np.array([[1, 2]])

print(f'v={v}')

v=[[1 2]]


A column vector can be instanted from a list of singleton *lists*. For instance, for 
$$\myvec{u} = \left[\begin{array}{ccc}
         1 \\
         2
        \end{array}\right],$$
we have

In [227]:
import numpy as np 

# Note that each row is defined by a single element within a [], while the whole vector is within an external []
u = np.array([[1],
              [2]])

print(f'u={u}')

u=[[1]
 [2]]


### Dot product

$$\myvec{c} = <\myvec{u},\myvec{u}>$$

In [228]:
import numpy as np

c = np.vdot(u,u)

print(f'c={c}')

c=5


### Euclidean norm

$$\myvec{c} = ||\myvec{u}||$$

<div class="alert alert-block alert-info">
Note that the function is np.<b>linalg</b>.norm, as the norm calculation is within the module <b>linalg</b>.
</div>

In [229]:
import numpy as np

c = np.linalg.norm(u)

print(f'c={c}')

c=2.23606797749979


### Instantiating matrices
For instance, suppose that we want to instanteate two real square matrices
$$\mymatrix{A} = \left[\begin{array}{ccc}
         1 & 2 \\
         3 & 4 
        \end{array}\right],
\mymatrix{B} = \left[\begin{array}{ccc}
        5 & 6 \\
        7 & 8 
        \end{array}\right]
$$

In [230]:
import numpy as np 

A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[5, 6], 
              [7, 8]])

print(f'A={A},\n\nB={B}')

A=[[1 2]
 [3 4]],

B=[[5 6]
 [7 8]]


### Transpose

$$\mymatrix{C} = \mymatrix{A}^T$$

In [231]:
import numpy as np 

C = A.T

print(f'C={C}')

C=[[1 3]
 [2 4]]


### Sum

$$ \mymatrix{C} = \mymatrix{A} + \mymatrix{B} $$

In [232]:
import numpy as np 

C = A + B

print(f'C={C}')

C=[[ 6  8]
 [10 12]]


### Subtraction

$$ \mymatrix{C} = \mymatrix{A} - \mymatrix{B} $$

In [233]:
import numpy as np 

C = A - B

print(f'C={C}')

C=[[-4 -4]
 [-4 -4]]


### Matrix multiplication

For instance,
$$C = A.B$$
is implemented with

<div class="alert alert-block alert-info">
The matrix multiplication operator, <b>@</b>, is very unusual. Pay close attention.
Mistaking this can be a major source of bugs and confusion.
</div>

In [234]:
import numpy as np 

C = A @ B # Alternatively C = np.matmul(A,B), but that is too verbose

print(f'C={C}')

C=[[19 22]
 [43 50]]


which will naturally work for the vectors we defined. For example
$$\myvec{c} = \myvec{u}.\myvec{v} = \left[\begin{array}{ccc}
         1 & 2 \\
         2 & 4 
        \end{array}\right],
$$
$$ \myvec{d} = \myvec{v}.\myvec{u} = 5.
$$

In [235]:
import numpy as np 

c = u @ v 
d = v @ u 

print(f'c={c},\n\nd={d}')

c=[[1 2]
 [2 4]],

d=[[5]]


and, of course, matrices and vectors

$$ \myvec{c} = \myvec{A}\myvec{u} $$

<div class="alert alert-block alert-info">
We only use the "." sign to denote matrix multiplication when otherwise it would be difficult to read the equation.
</div>

In [236]:
import numpy as np 

c = A @ u 

print(f'c={c},\n')

c=[[ 5]
 [11]],



### Diagonal matrices

Diagonal matrices get increasingly sparse with size, so it is important to have shorthanded commands for creating them. For instance, suppose that we have the following diagonal matrix

$$\mymatrix{D} = \left[\begin{array}{ccc}
         1 & 0 & 0 \\
         0 & 2 & 0 \\
         0 & 0 & 3   
        \end{array}\right] ,
$$

this can be instanteated in `numpy` with

In [237]:
import numpy as np 

D = np.diag([1, 2, 3])

print(f'D={D}.')

D=[[1 0 0]
 [0 2 0]
 [0 0 3]].


### Identity matrix

Among frequently used diagonal matrices, the identity matrix appears frequently. For instance, 

$$ \mymatrix{I}_3 = \left[\begin{array}{ccc}
         1 & 0 & 0 \\
         0 & 1 & 0 \\
         0 & 0 & 1   
        \end{array}\right],
$$ 

can be instanteated in `numpy` with

In [238]:
import numpy as np 

I_3 = np.eye(3)

print(f'I_3={I_3}.')

I_3=[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]].


### Zero matrix

Another frequently used matrix is the zero matrix. For instance,

$$ \mymatrix{O}_3 = \left[\begin{array}{ccc}
         0 & 0 & 0 \\
         0 & 0 & 0 \\
         0 & 0 & 0   
        \end{array}\right],
$$ 

<div class="alert alert-block alert-info">
The <b>np.zeros</b> function takes a tuple to generate a properly sized matrix. Do not confuse it with <b>np.eye</b> that accepts a scalar.
</div>

In [239]:
import numpy as np 

O_3 = np.zeros((3,3))

print(f'O_3={O_3}.')

O_3=[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]].


# The Robotics Toobox for Python
In this unit, we will frequently rely on [`Robotics Toolbox for Python`](https://github.com/petercorke/robotics-toolbox-python), by Peter Corke and contributors.

This powerful toolbox will allow to perform robotics operations. 

In [240]:
%pip install roboticstoolbox-python --break-system-packages

  Using cached roboticstoolbox_python-1.1.1-cp312-cp312-macosx_14_0_arm64.whl
  Using cached spatialgeometry-1.1.0-cp312-cp312-macosx_14_0_arm64.whl
  Using cached swift_sim-1.1.0-cp312-cp312-macosx_14_0_arm64.whl
  Using cached rtb_data-1.0.1-py3-none-any.whl
  Using cached progress-1.6-py3-none-any.whl
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
  Using cached numpy-1.26.4-cp312-cp312-macosx_11_0_arm64.whl.metadata (61 kB)
  Using cached matplotlib-3.5.1-cp312-cp312-macosx_14_0_arm64.whl
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Using cached cfgv-3.4.0-py2.py3-none-any.whl.metadata (8.5 kB)
  Using cached nodeenv-1.9.1-py2.py3-none-any.whl.metadata (21 kB)
  Using cached PyYAML-6.0.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (2.1 kB)
  Using cached distlib-0.3.9-py2.py3-none-any.whl.metadata (5.2 kB)
Using cached numpy-1.26.4-cp312-cp312-macosx_11_0_arm64.whl (13.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.9/24.9 MB 32.