# L3 Exercise Answers

*License: CC-BY-NC-SA 4.0*

### I found an issue
Thank you! Please report it at https://github.com/MarinhoLab/OpenExecutableBooksRobotics/issues

### Latex Macros

$\providecommand{\myvec}[1]{{\mathbf{\boldsymbol{{#1}}}}}$
$\providecommand{\mymatrix}[1]{{\mathbf{\boldsymbol{{#1}}}}}$

# Valid imports

In [8]:
from math import pi, sin, cos
import numpy as np

# Exercises

## Exercise a

In [9]:
q_A0 = pi/4.0 # As given in the exercise
q_A1 = -0.1 # As given in the exercise

H_A0_A0p = np.array(
    [[cos(q_A0), -sin(q_A0), 0, 0],
    [sin(q_A0),  cos(q_A0), 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]]
)

H_A0p_A0pp = np.array(
    [[1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0.5],
    [0, 0, 0, 1]]
)

H_A0pp_A1 = np.array(
    [[1, 0, 0, 0],
    [0, cos(pi/2), -sin(pi/2), 0],
    [0, sin(pi/2),  cos(pi/2), 0],
    [0, 0, 0, 1]]
)

H_A1_A2 = np.array(
    [[1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, q_A1],
    [0, 0, 0, 1]]
)


H_A0_A2 = H_A0_A0p @ H_A0p_A0pp @ H_A0pp_A1 @ H_A1_A2

# Printing the result is NOT a mandatory part of the answer.
print(f'H_A0_A2 = {H_A0_A2}')

H_A0_A2 = [[ 7.07106781e-01 -4.32978028e-17  7.07106781e-01 -7.07106781e-02]
 [ 7.07106781e-01  4.32978028e-17 -7.07106781e-01  7.07106781e-02]
 [ 0.00000000e+00  1.00000000e+00  6.12323400e-17  5.00000000e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


## Exercise c

In [10]:
# All rotations are the same
H_Rz = np.array(
    [[cos(pi/5.0), -sin(pi/5.0),  0, 0],
     [sin(pi/5.0),  cos(pi/5.0),  0, 0],
     [0,          0,          1, 0],
     [0,          0,          0, 1]]
)

# All translations are the same
H_Tx = np.array(
    [[1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0.25],
    [0, 0, 0, 1]]
)

H_C0_C3 = H_Rz @ H_Tx @ H_Rz @ H_Tx @ H_Rz @ H_Tx

# Printing the result is NOT a mandatory part of the answer.
print(f'H_C0_C3 = {H_C0_C3}')

H_C0_C3 = [[-0.30901699 -0.95105652  0.          0.        ]
 [ 0.95105652 -0.30901699  0.          0.        ]
 [ 0.          0.          1.          0.75      ]
 [ 0.          0.          0.          1.        ]]
